"""changed publishers_books table name

Revision ID: f7149fd24eb1
Revises:
Create Date: 2022-02-24 09:40:06.076231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123456789abc'
down_revision = 'f7149fd24eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('publishers_books', 'publisher_books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('publisher_books', 'publishers_books')
    # ### end Alembic commands ###
