"""empty message

Revision ID: 7d1fc948af69
Revises: 123456789abc
Create Date: 2022-02-24 10:11:14.341280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1fc948af69'
down_revision = '123456789abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishers', 'location', new_column_name='city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishers', 'city', new_column_name='location')
    # ### end Alembic commands ###
